### PR TITLE
Enable Google Analytics on Try Zeek

### PR DESCRIPTION
**Pull request by devbali**
This enables Google Analytics on Try Zeek for better data on who is using the tutorial.

### CODE REVIEW

**Comment by rsmmr** [comment]
@JustinAzoff can you look into this and merge and/or close? Thanks.

**Comment by rsmmr** [comment]
Guess this is not going to happen, closing. @JustinAzoff

**Comment by JustinAzoff** [comment]
Oh!  I did look into this.. I found that try.zeek.org includes the https://www.zeek.org/frames/header.html in an iframe which includes that analytics code.  I meant to ask if we were possibly already getting the data that we wanted.

**Comment by rsmmr** [comment]
Ah, interesting. @akgraner are we seeing analytics data from try.zeek.org already?

**Comment by akgraner** [comment]
@rsmmr doesn't look like we are getting data from try.zeek.org. Who can I send the information so that we can get that added? You or @JustinAzoff

**Comment by rsmmr** [comment]
@JustinAzoff please

**Comment by rsmmr** [comment]
No progress, closing again.

**Pull request closed without merging**
