### PR TITLE
Client-side source code validation 

### PR DESCRIPTION
**Pull request by bbannier**
https://github.com/zeek/try-zeek/assets/324957/13e4be01-da1f-4cb3-846d-20d0252fb9e3

### CODE REVIEW

**Comment by bbannier** [comment]
@JustinAzoff This is a draft implementation of the client-side source code validation I had mentioned over in #70. I manually checked that this works as expected, but have no practical experience in React (much less Redux), so any feedback would be more that welcome.

**Review by timwoj — APPROVED** [review]
I definitely like the idea of this. I imagine that most peoples' initial experience with writing Zeek scripts comes through try-zeek, and helping them with simple mistakes is a good thing.

**Comment by JustinAzoff** [comment]
https://github.com/user-attachments/assets/b2d46bbf-7b47-4079-ba69-3c44324441c7

**Comment by bbannier** [comment]
> Screen.Recording.2024-07-15.at.4.20.56.PM.mov

I cannot reproduce it and am a bit out of my depth assessing what is going on here. I put in an extra `reset` into `check_syntax` to clear any previous parser state, but if that shouldn't fix it I suspect it might be a general issue in the state handling.

**Comment by bbannier** [comment]
TBH, if this is too much hassle it might be worth to instead abandon this completely and have someone look into https://github.com/mkslanc/ace-linters to set up proper diagnostics from a LSP instance running in the server (would require adding websockets support to bbannier/zeek-language-server).

**Comment by bbannier** [comment]
Closing this as there seems no interest in this.

**Pull request closed without merging**
